### ISSUE TITLE
Library jar on oss.sonatype.org appears to bundle classfiles instrumented by scoverage

### ISSUE THREAD

**Issue by mallman** [reactivecodes/scala-time#10]
When I try to run an assembly which bundles scalatime 0.4.0-SNAPSHOT downloaded from oss.sonatype.org I get

    java.lang.NoClassDefFoundError: scoverage/Invoker$
      at codes.reactive.scalatime.impl.ToTemporalOps$class.toTemporalOpsFromTemporal(TemporalOps.scala:92)
      at codes.reactive.scalatime.impl.ToAllOps.toTemporalOpsFromTemporal(ToAllOps.scala:22)

The underlying issue appears to be related to https://github.com/scoverage/sbt-scoverage/issues/115.

**Comment by mallman** [comment]
BTW I tried resolving this by adding the scoverage runtime to my classpath without success. This time I got a different error:

```
java.io.FileNotFoundException: /home/arashi01/Projects/scala-time/target/scala-2.11/scoverage-data/scoverage.measurements.1 (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileWriter.<init>(FileWriter.java:107)
	at scoverage.Invoker$$anonfun$1.apply(Invoker.scala:45)
	at scoverage.Invoker$$anonfun$1.apply(Invoker.scala:45)
	at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:901)
	at scoverage.Invoker$.invoked(Invoker.scala:45)
	at codes.reactive.scalatime.impl.ToTemporalOps$class.toTemporalOpsFromTemporal(TemporalOps.scala:92)
	at codes.reactive.scalatime.impl.ToAllOps.toTemporalOpsFromTemporal(ToAllOps.scala:22)
```

**Comment by arashi01** [comment]
@mallman thanks for the report. I've published updated jars to Sonatype which should solve the issue.
